export { default as StartScreen } from './initial'
export { default as Login } from './login'
export { default as Dashboard } from './dashboard'
export { default as Config } from "./config";
export { default as Notificações } from "./notificações"
export { default as Dados } from "./dados"
export { default as Perfil } from "./perfil"
export { default as Documentos } from "./documentos"
export { default as Boletim } from "./boletim"
export { default as Turmas } from "./turmas"
export { default as Calendario } from "./calendario"
